name: Simple build

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
    - uses: gradle/actions/setup-gradle@v4
    - uses: docker/setup-buildx-action@v3
    - name: Build and test
      run: ./gradlew build
